export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
 
import "./styles/app.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {


  return (
    <html lang="en"> 
    <head> 
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
    <link href="https://fonts.googleapis.com/css2?family=Edu+SA+Beginner:wght@500;600&family=Nunito:ital@1&display=swap" rel="stylesheet"/>
    </head>
      <body className={inter.className}  style={{background: `url(/images/2302176_7981.jpg)`,backgroundPosition:"cover",backgroundRepeat:"no-repeat",backgroundSize:"cover"}}>{children}</body>
    </html>
  );
}
