export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Image from "next/image";
import "./styles/app.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+SA+Beginner:wght@500;600&family=Nunito:ital@1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Image
          src={"/images/2302176_7981.jpg"}
          height={1000}
          width={1000}
          style={{
            position: "fixed",
            zIndex: -1,
            top: 0,
            left: 0,
            bottom: 0,
            right: 0,
            objectFit: "cover",
            width: "100%",
            height: "100%",
          }}
        />
        {children}
      </body>
    </html>
  );
}
